# Generated by Django 3.1.6 on 2021-02-17 20:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200903_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-add_time'], 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AlterField(
            model_name='news',
            name='add_time',
            field=models.DateTimeField(verbose_name='Yayımlanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
